# Generated by Django 5.2.7 on 2025-10-22 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shortener", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="urldata",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
