# Generated by Django 5.2.7 on 2025-10-24 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shortener", "0002_urldata_is_deleted"),
    ]

    operations = [
        migrations.AlterField(
            model_name="urlclick",
            name="user_agent",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="urldata",
            name="slug",
            field=models.CharField(db_index=True, max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name="urldata",
            name="url",
            field=models.URLField(max_length=2048),
        ),
    ]
