# Generated by Django 5.2.7 on 2025-10-24 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shortener", "0003_alter_urlclick_user_agent_alter_urldata_slug_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="urldata",
            name="click_count",
        ),
    ]
