# Generated by Django 5.2.7 on 2025-10-25 16:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shortener", "0004_remove_urldata_click_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="urldata",
            name="create_time",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
