# Generated by Django 5.2.7 on 2025-10-26 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shortener", "0005_urldata_create_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="urlclick",
            name="user_browser",
            field=models.CharField(blank=True),
        ),
        migrations.AddField(
            model_name="urlclick",
            name="user_device",
            field=models.CharField(blank=True),
        ),
        migrations.AddField(
            model_name="urlclick",
            name="user_is_mobile",
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
