# Generated by Django 5.2.7 on 2025-10-26 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shortener", "0006_urlclick_user_browser_urlclick_user_device_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="urlclick",
            name="user_os",
            field=models.CharField(blank=True),
        ),
    ]
